package br.com.converter.main;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * @author Lucas Laet - 2020 - MIPS .txt document converter to binary computer
 *         language .txt document Made for Computers Architecture disciplin
 * @Class class that receive a .txt document and interfaces with client
 */
public class TextReader extends javax.swing.JFrame {

	private final JFileChooser openFileChooser;
	private List<String> txtDocument;

	/**
	 * Creates new form MainFrame
	 */
	public TextReader() {
		// init JPanel components
		initComponents();
		// instance JFileChooser for building a directory files path to be chosen
		openFileChooser = new JFileChooser();
		openFileChooser.setCurrentDirectory(new File("c:\\temp"));
		// set the files type to being referenced at directory
		openFileChooser.setFileFilter(new FileNameExtensionFilter("TEXT FILES", "txt", "text"));
		// disable visibility of progress bar
		setProgressBarVisibility(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		btnOpenFile = new javax.swing.JButton();
		progressBar = new javax.swing.JProgressBar();

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 100, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 100, Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
		jLabel1.setText("       MIPS CONVERTER");

		btnOpenFile.setBackground(new java.awt.Color(204, 0, 0));
		btnOpenFile.setForeground(new java.awt.Color(255, 255, 255));
		btnOpenFile.setText("Open TXT File");
		btnOpenFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnOpenFile.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnOpenFileActionPerformed(evt);
			}
		});

		progressBar.setForeground(new java.awt.Color(0, 0, 204));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(63, 63, 63).addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(126, 126, 126).addComponent(btnOpenFile))
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(95, 95, 95).addComponent(progressBar,
								javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(67, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 21,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(btnOpenFile)
						.addGap(39, 39, 39)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	/*
	 * When decode button is pressed get .txt file and call TextWriter @Class
	 */
	private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnOpenFileActionPerformed
		int returnValue = openFileChooser.showOpenDialog(this);
		// verify if there was a file chosen
		if (returnValue == JFileChooser.APPROVE_OPTION) {
			try {
				setButtonVisibility(false);
				// show progress bar
				setProgressBarVisibility(true);
				// set on progress bar display
				progressBar.setStringPainted(true);
				txtDocument = new ArrayList<>();
				// scanner receive .txt document
				Scanner qv = new Scanner(openFileChooser.getSelectedFile());
				// insert the document lines to list
				while (qv.hasNextLine()) {
					txtDocument.add(qv.nextLine().toUpperCase());
				}
				// close Scanner object
				qv.close();
				setProgressBarPercentage(15);
				// instance TextWriter class to write a new document
				TextWriter writer = new TextWriter(txtDocument);
				writer.writeDecodedTextDocument();
				setProgressBarPercentage(100);
				JOptionPane.showMessageDialog(null, "Proccess sucessfully concluded. The file named"
						+ " decoded-instructions.txt is avaliable on project directory.");
				progressBar.setVisible(false);
				setButtonVisibility(true);
			} catch (IOException ioe) {
				JOptionPane.showMessageDialog(null, ioe);
			}
		} else {
			JOptionPane.showMessageDialog(null, "Please, select a .txt file.");
		}
	}// GEN-LAST:event_btnOpenFileActionPerformed

	/*
	 * set the percentage value of the progress bar
	 */
	public void setProgressBarPercentage(int percentage) {
		progressBar.setValue(percentage);
	}

	/*
	 * set the progress bar visibility
	 */
	private void setProgressBarVisibility(Boolean visibility) {
		progressBar.setVisible(visibility);
	}

	/*
	 * set the open button visibility
	 */
	private void setButtonVisibility(Boolean visibility) {
		btnOpenFile.setVisible(visibility);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TextReader.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TextReader.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TextReader.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TextReader.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TextReader().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnOpenFile;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JProgressBar progressBar;
	// End of variables declaration//GEN-END:variables
}
